import type { LucideIcon } from 'lucide-react'
import {
  Bell,
  BookOpen,
  DoorOpen,
  Eye,
  Flag,
  Gamepad2,
  Map,
  MessagesSquare,
  MoonStar,
  ScrollText,
  Shield,
  Swords,
  UserRound,
  Users,
} from 'lucide-react'

const PRIME_ICON_BY_FA_NAME: Record<string, string> = {
  'fa-address-book': 'pi pi-address-book',
  'fa-address-card': 'pi pi-id-card',
  'fa-align-left': 'pi pi-align-left',
  'fa-arrow-down-wide-short': 'pi pi-sort-amount-down',
  'fa-arrow-right': 'pi pi-arrow-right',
  'fa-arrow-right-to-bracket': 'pi pi-sign-in',
  'fa-arrow-up-wide-short': 'pi pi-sort-amount-up',
  'fa-at': 'pi pi-at',
  'fa-ban': 'pi pi-ban',
  'fa-bars': 'pi pi-bars',
  'fa-bell': 'pi pi-bell',
  'fa-book-open': 'pi pi-book',
  'fa-calendar-day': 'pi pi-calendar',
  'fa-chevron-left': 'pi pi-chevron-left',
  'fa-chevron-right': 'pi pi-chevron-right',
  'fa-chevron-up': 'pi pi-chevron-up',
  'fa-circle-check': 'pi pi-check-circle',
  'fa-circle-info': 'pi pi-info-circle',
  'fa-circle-notch': 'pi pi-spin pi-spinner',
  'fa-circle-plus': 'pi pi-plus-circle',
  'fa-circle-xmark': 'pi pi-times-circle',
  'fa-clipboard-list': 'pi pi-list',
  'fa-code-branch': 'pi pi-share-alt',
  'fa-comment-dots': 'pi pi-comment',
  'fa-comments': 'pi pi-comments',
  'fa-copy': 'pi pi-copy',
  'fa-diagram-project': 'pi pi-sitemap',
  'fa-dice-d20': 'pi pi-star',
  'fa-door-open': 'pi pi-door-open',
  'fa-dungeon': 'pi pi-building',
  'fa-eye': 'pi pi-eye',
  'fa-eye-slash': 'pi pi-eye-slash',
  'fa-filter': 'pi pi-filter',
  'fa-flag-checkered': 'pi pi-flag',
  'fa-floppy-disk': 'pi pi-save',
  'fa-folder-open': 'pi pi-folder-open',
  'fa-gamepad': 'pi pi-microsoft',
  'fa-gavel': 'pi pi-hammer',
  'fa-hashtag': 'pi pi-hashtag',
  'fa-hourglass-half': 'pi pi-clock',
  'fa-id-card': 'pi pi-id-card',
  'fa-image': 'pi pi-image',
  'fa-instagram': 'pi pi-instagram',
  'fa-key': 'pi pi-key',
  'fa-layer-group': 'pi pi-th-large',
  'fa-link': 'pi pi-link',
  'fa-list': 'pi pi-list',
  'fa-list-check': 'pi pi-check-square',
  'fa-lock': 'pi pi-lock',
  'fa-magnifying-glass': 'pi pi-search',
  'fa-map-location-dot': 'pi pi-map-marker',
  'fa-mask': 'pi pi-user-edit',
  'fa-minus': 'pi pi-minus',
  'fa-moon': 'pi pi-moon',
  'fa-paper-plane': 'pi pi-send',
  'fa-pen': 'pi pi-pencil',
  'fa-pen-to-square': 'pi pi-pencil',
  'fa-people-group': 'pi pi-users',
  'fa-phone': 'pi pi-phone',
  'fa-plus': 'pi pi-plus',
  'fa-quote-left': 'pi pi-quote-left',
  'fa-quote-right': 'pi pi-quote-right',
  'fa-right-from-bracket': 'pi pi-sign-out',
  'fa-right-left': 'pi pi-arrow-right-arrow-left',
  'fa-rotate': 'pi pi-refresh',
  'fa-rotate-left': 'pi pi-replay',
  'fa-rotate-right': 'pi pi-refresh',
  'fa-shield-halved': 'pi pi-shield',
  'fa-signature': 'pi pi-pencil',
  'fa-sliders': 'pi pi-sliders-h',
  'fa-sort': 'pi pi-sort-alt',
  'fa-stopwatch': 'pi pi-clock',
  'fa-sun': 'pi pi-sun',
  'fa-table-list': 'pi pi-table',
  'fa-toggle-off': 'pi pi-toggle-off',
  'fa-toggle-on': 'pi pi-toggle-on',
  'fa-triangle-exclamation': 'pi pi-exclamation-triangle',
  'fa-unlock': 'pi pi-lock-open',
  'fa-unlock-keyhole': 'pi pi-lock-open',
  'fa-user': 'pi pi-user',
  'fa-user-check': 'pi pi-user-plus',
  'fa-user-gear': 'pi pi-cog',
  'fa-user-pen': 'pi pi-user-edit',
  'fa-user-shield': 'pi pi-shield',
  'fa-user-slash': 'pi pi-user-minus',
  'fa-users': 'pi pi-users',
  'fa-wand-magic-sparkles': 'pi pi-sparkles',
  'fa-whatsapp': 'pi pi-whatsapp',
  'fa-xmark': 'pi pi-times',
}

const LUCIDE_ICON_BY_NAME: Record<string, LucideIcon> = {
  Bell,
  BookOpen,
  DoorOpen,
  Eye,
  Flag,
  Gamepad2,
  Map,
  MessagesSquare,
  MoonStar,
  ScrollText,
  Shield,
  Swords,
  UserRound,
  Users,
}

function resolvePrimeIcon(name: string) {
  if (name.includes('pi ')) return name
  const tokens = name.split(/\s+/).filter(Boolean)
  const matched = [...tokens].reverse().find((token) => token.startsWith('fa-') && token !== 'fa-solid' && token !== 'fa-brands')
  return (matched && PRIME_ICON_BY_FA_NAME[matched]) || 'pi pi-circle'
}

export function Icon({ name, className = '' }: { name: string; className?: string }) {
  if (name.startsWith('lucide:')) {
    const iconName = name.slice('lucide:'.length)
    const LucideComponent = LUCIDE_ICON_BY_NAME[iconName]
    if (LucideComponent) {
      return <LucideComponent aria-hidden="true" className={`app-icon-lucide ${className}`.trim()} strokeWidth={2} />
    }
  }
  return <i aria-hidden="true" className={`${resolvePrimeIcon(name)} ${className}`.trim()} />
}
